In [1]:
import numpy  as np

In [6]:
multi_dim=np.array([[324,454,341],[123,90,456],[64,7,93]])
print(multi_dim.ndim)
print(multi_dim.shape)
print(multi_dim)

2
(3, 3)
[[324 454 341]
 [123  90 456]
 [ 64   7  93]]


In [5]:
#Sort the  array
np.sort(multi_dim,axis=1,kind="mergesort")

array([[324, 341, 454],
       [ 90, 123, 456],
       [  7,  64,  93]])

In [7]:
np.sort(multi_dim,axis=0,kind="mergesort")

array([[ 64,   7,  93],
       [123,  90, 341],
       [324, 454, 456]])

In [8]:
np.sort(multi_dim,axis=0,kind="quicksort")

array([[ 64,   7,  93],
       [123,  90, 341],
       [324, 454, 456]])