In [1]:
import numpy as np

In [2]:
arr1=np.array([[1,2,3,4],
               [5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr2=np.array([[12,34,56,98],
               [9,11,33,54]])
arr2

array([[12, 34, 56, 98],
       [ 9, 11, 33, 54]])

In [5]:
#To concatenate 2 array we have "H stack" and "V stack"
#Vertical(V) Stack"
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [12, 34, 56, 98],
       [ 9, 11, 33, 54]])

In [6]:
np.vstack((arr2,arr1))

array([[12, 34, 56, 98],
       [ 9, 11, 33, 54],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [7]:
#Horizontal(H) stack
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 12, 34, 56, 98],
       [ 5,  6,  7,  8,  9, 11, 33, 54]])

In [10]:
np.hstack((arr2,arr1))

array([[12, 34, 56, 98,  1,  2,  3,  4],
       [ 9, 11, 33, 54,  5,  6,  7,  8]])

In [16]:
test1=np.concatenate((arr1,arr2),axis=0) #If the axis=0 they are "Vertically" stacked
test1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [12, 34, 56, 98],
       [ 9, 11, 33, 54]])

In [17]:
np.concatenate((arr1,arr2),axis=1) #If the axis=1 they are "Horizontally" stacked

array([[ 1,  2,  3,  4, 12, 34, 56, 98],
       [ 5,  6,  7,  8,  9, 11, 33, 54]])

In [20]:
#We can split an array using "H split" and "V split"
np.hsplit(test1,2)

[array([[ 1,  2],
        [ 5,  6],
        [12, 34],
        [ 9, 11]]),
 array([[ 3,  4],
        [ 7,  8],
        [56, 98],
        [33, 54]])]

In [21]:
np.vsplit(test1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[12, 34, 56, 98],
        [ 9, 11, 33, 54]])]

In [4]:
gfg=np.arange(9).reshape(3,3)
gfg


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
gfg2=np.vsplit(gfg,1)
gfg2

[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])]

In [12]:
gfg2=np.hsplit(gfg,3)
gfg2

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]