In [1]:
import numpy as np

In [7]:
arr_one_d=np.array([1,2,3,4,5,6])
print(arr_one_d[1])
print(arr_one_d[2])
print(arr_one_d[3])

2
3
4


In [10]:
print(arr_one_d[:-3])
print(arr_one_d[:-1])
print(arr_one_d[::-1])

[1 2 3]
[1 2 3 4 5]
[6 5 4 3 2 1]


In [2]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [3]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [13]:
arr1[1:3 , 1:3]

array([[6, 7],
       [7, 6]])

In [16]:
arr1[2,:]

array([8, 7, 6, 5])

In [17]:
arr1[:,3]

array([4, 8, 5, 1])

In [18]:
arr1[1:,1:2]

array([[6],
       [7],
       [3]])