In [1]:
import numpy  as np

In [2]:
arr=np.array([-14,-32,1,3,4,5,6,7,43,645,3332,4343])
arr

array([ -14,  -32,    1,    3,    4,    5,    6,    7,   43,  645, 3332,
       4343])

In [3]:
print(arr - 1)
print(arr + 1)
print(arr * 7)
print(arr % 2)
print(arr / 2)
print(arr ** 2)

[ -15  -33    0    2    3    4    5    6   42  644 3331 4342]
[ -13  -31    2    4    5    6    7    8   44  646 3333 4344]
[  -98  -224     7    21    28    35    42    49   301  4515 23324 30401]
[0 0 1 1 0 1 0 1 1 1 0 1]
[-7.0000e+00 -1.6000e+01  5.0000e-01  1.5000e+00  2.0000e+00  2.5000e+00
  3.0000e+00  3.5000e+00  2.1500e+01  3.2250e+02  1.6660e+03  2.1715e+03]
[     196     1024        1        9       16       25       36       49
     1849   416025 11102224 18861649]


In [4]:
print(arr.max())

4343


In [5]:
print(arr.min())

-32


In [6]:
arr = np.array([[21,7,23],[4,55,6],[7,8,29]])
arr

array([[21,  7, 23],
       [ 4, 55,  6],
       [ 7,  8, 29]])

In [7]:
print(arr.max())

55


In [8]:
#How to get the maximum value of an array in row and column wise
arr.max(axis=0) #In axis=0 we will get the maximum element of column

array([21, 55, 29])

In [9]:
arr.max(axis=1) #In axis=1 we will get the maximum element of row

array([23, 55, 29])

In [10]:
arr.min(axis=0)

array([4, 7, 6])

In [11]:
arr.min(axis=1)

array([7, 4, 7])

In [12]:
#sum of all the element of array
arr.sum()

160

In [13]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr3=np.array([[9,10,11,12],[3,14,15,16]])
arr3

array([[ 9, 10, 11, 12],
       [ 3, 14, 15, 16]])

In [15]:
arr2 + arr3 

array([[10, 12, 14, 16],
       [ 8, 20, 22, 24]])

In [16]:
arr2 * arr3

array([[  9,  20,  33,  48],
       [ 15,  84, 105, 128]])

In [17]:
#Dot(.) operation on array
arr1=np.array([[1,2,3],
               [5,6,7],
               [9,10,11]])
arr1

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [18]:
arr2=np.array([[34,32,78],
               [22,34,5],
               [13,90,54]])
arr2

array([[34, 32, 78],
       [22, 34,  5],
       [13, 90, 54]])

In [19]:
print((1*34) + (2*22) + (3*13))
print((1*32) + (2*34) + (3*90))
print((1*78)+(2*5)+(3*54))

117
370
250


In [20]:
arr1.dot(arr2)

array([[ 117,  370,  250],
       [ 393,  994,  798],
       [ 669, 1618, 1346]])

In [21]:
arr2.dot(arr1)

array([[ 896, 1040, 1184],
       [ 237,  298,  359],
       [ 949, 1106, 1263]])

In [22]:
#indexing
arr=np.array([1,2,3,4,5])
arr[1]

2

In [23]:
arr[-1]

5

In [24]:
arr[0:3]

array([1, 2, 3])

In [58]:
arr[2:-1]

array([3, 4])

In [59]:
arr[:-2]

array([1, 2, 3])

In [60]:
arr2 

array([[34, 32, 78],
       [22, 34,  5],
       [13, 90, 54]])

In [65]:
arr2[1][1]

34

In [77]:
arr2

array([[34, 32, 78],
       [22, 34,  5],
       [13, 90, 54]])

In [87]:
arr2[ 1:3, 1:2 ] 

array([[34],
       [90]])

In [37]:
arr2[0:2,0:2] 

array([[34, 32],
       [22, 34]])

In [38]:
arr2[1:2,1:2]

array([[34]])