In [2]:
import numpy as np
lsst1=[1,2,3,4,5,6,7,8]

In [2]:
count=0
for i in lsst1:
    if i >5:
        count +=1
    
print(count)

3


In [3]:
arr1=np.array(lsst1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
arr1 > 5

array([False, False, False, False, False,  True,  True,  True])

In [11]:
#Check how many element in a array are greater than 5
arr1[arr1 > 5]

array([6, 7, 8])

In [12]:
arr1[arr1 > 5].size

3

In [15]:
#Check how many element in an array are divisible by 3
print(arr1[arr1 % 3 ==0])
print(arr1[arr1 % 3 ==0].size)

[3 6]
2


In [16]:
arr2=np.array([1,2,3,"Prajesh",4,5,"Waghela"])
arr2

array(['1', '2', '3', 'Prajesh', '4', '5', 'Waghela'], dtype='<U11')

In [30]:
ui_name=input("Enter the name of the user:")
contains_user_name=arr2[arr2 == ui_name]
if contains_user_name:
    print("User already exists")
else:
    print("Please create the user")

Please create the user


C:\Users\Admin\AppData\Local\Temp\ipykernel_2456\3261396931.py:3: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if contains_user_name:


In [32]:
arr4=np.array((1,2,3,4))

In [33]:
arr4.dtype

dtype('int32')

In [3]:
c=np.array([6,7,5,8])
d=np.array([4,3,7,8])
pro=c.dot(d)
print(pro)

144


In [4]:
trz=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
trz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
trz.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [6]:
trz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
trz.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [8]:
trz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
a1=np.array([[1,2],[3,4]])
b1=np.array([[5,6]])

In [4]:
b1.T

array([[5],
       [6]])

In [ ]:
np.concatenate((a1,b1.T),axis=1)