## Reshape and Random number Generator

In [1]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])

In [3]:
a.ndim

2

In [5]:
##Generate a Random Numbers

In [27]:
arr1=np.random.random((3,3))
arr1

array([[0.39549606, 0.2163898 , 0.94357395],
       [0.66233299, 0.65926919, 0.44771754],
       [0.68323194, 0.79319593, 0.05224586]])

In [28]:
np.random.random()

0.47836776866833874

In [29]:
if np.random.random() > 0.5:
    print("Run the Function")
else:
    print("Don't run the function")

Run the Function


In [30]:
##Generate a number in particular sequence
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np.linspace(1,10,35)

array([ 1.        ,  1.26470588,  1.52941176,  1.79411765,  2.05882353,
        2.32352941,  2.58823529,  2.85294118,  3.11764706,  3.38235294,
        3.64705882,  3.91176471,  4.17647059,  4.44117647,  4.70588235,
        4.97058824,  5.23529412,  5.5       ,  5.76470588,  6.02941176,
        6.29411765,  6.55882353,  6.82352941,  7.08823529,  7.35294118,
        7.61764706,  7.88235294,  8.14705882,  8.41176471,  8.67647059,
        8.94117647,  9.20588235,  9.47058824,  9.73529412, 10.        ])

In [33]:
## Reshape
arr2=np.random.random((4,3))
arr2

array([[0.17501323, 0.8591286 , 0.89317522],
       [0.24140568, 0.13806344, 0.20855007],
       [0.42206829, 0.82424825, 0.8818906 ],
       [0.17154542, 0.85851845, 0.43757937]])

In [37]:
arr2=np.reshape(arr2,(3,4))
arr2

array([[0.17501323, 0.8591286 , 0.89317522, 0.24140568],
       [0.13806344, 0.20855007, 0.42206829, 0.82424825],
       [0.8818906 , 0.17154542, 0.85851845, 0.43757937]])

In [38]:
arr2=np.reshape(arr2,(2,6))
arr2

array([[0.17501323, 0.8591286 , 0.89317522, 0.24140568, 0.13806344,
        0.20855007],
       [0.42206829, 0.82424825, 0.8818906 , 0.17154542, 0.85851845,
        0.43757937]])

In [43]:
arr3=np.arange(8).reshape(2,2,2)
arr3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [39]:
arr2.flatten()

array([0.17501323, 0.8591286 , 0.89317522, 0.24140568, 0.13806344,
       0.20855007, 0.42206829, 0.82424825, 0.8818906 , 0.17154542,
       0.85851845, 0.43757937])

In [44]:
a1=np.array([[1,2,3,4],[5,6,7,8]])
a2=np.array([[5,67,7],[6,87,89]])
print(f"After flattering : {a1.flatten()}")
print(f"After flattering : {a2.flatten()}")

After flattering : [1 2 3 4 5 6 7 8]
After flattering : [ 5 67  7  6 87 89]
